# Generated by Django 4.2.6 on 2023-11-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=2)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateIssued', models.DateTimeField(auto_now_add=True)),
                ('laborHours', models.IntegerField()),
                ('laborRate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item1Desc', models.TextField()),
                ('item1Price', models.DecimalField(decimal_places=2, max_digits=100000000)),
                ('item1Qty', models.IntegerField()),
                ('item2Desc', models.TextField()),
                ('item2Price', models.DecimalField(decimal_places=2, max_digits=100000000)),
                ('item2Qty', models.IntegerField()),
                ('item3Desc', models.TextField()),
                ('item3Price', models.DecimalField(decimal_places=2, max_digits=100000000)),
                ('item3Qty', models.IntegerField()),
                ('Tax', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('plateNumber', models.CharField(max_length=10)),
            ],
        ),
    ]
