# Generated by Django 4.2.6 on 2024-04-01 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pay_period', models.DateField()),
                ('bank_account_info', models.CharField(blank=True, help_text='Information for wire transfer', max_length=255, null=True)),
            ],
        ),
    ]
