# Generated by Django 4.2.6 on 2024-04-01 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employees', '0001_initial'),
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.employee'),
        ),
    ]
