# Generated by Django 4.2.9 on 2024-03-29 15:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('clientName', models.CharField(max_length=200)),
                ('clientNumber', models.CharField(max_length=10)),
                ('clientEmail', models.EmailField(max_length=50)),
                ('message', models.CharField(max_length=500)),
                ('clientID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
