# Generated by Django 5.0.1 on 2024-04-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockNumber', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('partName', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
