# Generated by Django 4.2.11 on 2024-04-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
