from django.test import TestCase
# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCreatingAnInvoice():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_creatingAnInvoice(self):
    self.driver.get("https://capstone-deployment-production.up.railway.app/home/")
    self.driver.set_window_size(1296, 696)
    self.driver.find_element(By.LINK_TEXT, "Invoices").click()
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    self.driver.find_element(By.ID, "id_firstName").click()
    self.driver.find_element(By.ID, "id_firstName").send_keys("John")
    self.driver.find_element(By.ID, "id_lastName").send_keys("Doe")
    self.driver.find_element(By.ID, "id_address").send_keys("123 Lane")
    self.driver.find_element(By.ID, "id_city").send_keys("Washington")
    self.driver.find_element(By.ID, "id_state").send_keys("VA")
    self.driver.find_element(By.ID, "id_email").send_keys("johndoe@email.com")
    self.driver.find_element(By.ID, "id_type").click()
    self.driver.find_element(By.ID, "id_type").send_keys("sedan")
    self.driver.find_element(By.ID, "id_year").send_keys("2005")
    self.driver.find_element(By.ID, "id_make").send_keys("toyota")
    self.driver.find_element(By.ID, "id_model").send_keys("corolla")
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(6) > #id_firstName").send_keys("silver")
    self.driver.find_element(By.ID, "id_plateNumber").send_keys("ABC123")
    self.driver.find_element(By.ID, "id_laborHours").click()
    self.driver.find_element(By.ID, "id_laborHours").send_keys("5")
    self.driver.find_element(By.ID, "id_laborRate").send_keys("12.50")
    self.driver.find_element(By.ID, "id_item1Desc").send_keys("Wheels")
    self.driver.find_element(By.ID, "id_item1Price").send_keys("50")
    self.driver.find_element(By.ID, "id_item1Qty").send_keys("4")
    self.driver.find_element(By.ID, "id_item2Desc").send_keys("Motor")
    self.driver.find_element(By.ID, "id_item2Price").send_keys("500")
    self.driver.find_element(By.ID, "id_item2Qty").send_keys("1")
    self.driver.find_element(By.ID, "id_item3Desc").send_keys("Steering Wheel")
    self.driver.find_element(By.ID, "id_item3Price").send_keys("200")
    self.driver.find_element(By.ID, "id_item3Qty").send_keys("1")
    self.driver.find_element(By.ID, "id_totalLabor").click()
    self.driver.find_element(By.ID, "id_totalLabor").send_keys("62.50")
    self.driver.find_element(By.ID, "id_totalItems").click()
    self.driver.find_element(By.ID, "id_totalItems").send_keys("900")
    self.driver.find_element(By.ID, "id_totalNoTax").click()
    self.driver.find_element(By.ID, "id_totalNoTax").send_keys("962.5")
    self.driver.find_element(By.ID, "id_Tax").click()
    self.driver.find_element(By.ID, "id_Tax").send_keys("112.5")
    self.driver.find_element(By.ID, "id_totalPrice").click()
    self.driver.find_element(By.ID, "id_totalPrice").send_keys("1075")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
